/// A module providing workarounds for HTML features not supported by typst yet

#import "./html-toolkit.typ": asset-url

/// Display the linked URL in a new tab
///
/// Usage: `#show link: link-in-new-tab`
#let link-in-new-tab(class: none, it) = html.a(
  target: "_blank",
  href: it.dest,
  ..if class != none { (class: class) },
  it.body,
)

/// Use proportional-width apostrophes
///
/// The main font is for Chinese, so it uses full-width apostrophes by default.
/// For Latin texts, it is better to use proportional-width ones.
/// https://typst-doc-cn.github.io/guide/FAQ/smartquote-font.html#若中西统一使用相同字体
///
/// Usage: `#show: enable-proportional-width`
#let latin-apostrophe = html.span.with(style: "font-feature-settings: 'pwid';")

/// Externalize images in /public/
///
/// Usage: `#show image: external-image`
#let external-image(it) = {
  if type(it.source) == str and it.source.starts-with("/public/") {
    // Do not enable lazy loading here. Lazy images without explicit sizes will cause the page to flush, making links with hash anchors being unable to locate accurately.
    html.img(
      src: asset-url(it.source.trim("/public", at: start)),
      ..if it.alt != none { (alt: it.alt, title: it.alt) },
      ..if type(it.width) == relative { (style: "width:" + repr(it.width.ratio)) },
    )
  } else {
    it
  }
}

/// Parse a string into a length
/// Example: `"58.828pt"` → `58.828pt`
#let _pt(raw) = float(raw.trim("pt", at: end)) * 1pt

/// Externalize SVGs in /public/
/// Only SVGs generated by typst are tested.
///
/// Usage: `#show image: external-svg`
#let external-svg(it) = {
  if type(it.source) == str and it.source.starts-with("/public/") and it.source.ends-with(".svg") {
    let (width, height) = xml(it.source).first().attrs
    html.img(
      src: asset-url(it.source.trim("/public", at: start)),
      loading: "lazy",
      // Copy the behaviour of `html.frame`.
      // https://github.com/typst/typst/blob/6312c6636064466556fe79bb0bf5479977fafc9b/crates/typst-svg/src/lib.rs#L70-L77
      style: "overflow: visible; width: {width}em; height: {height}em;"
        .replace("{width}", str(_pt(width) / text.size))
        .replace("{height}", str(_pt(height) / text.size)),
    )
  } else {
    it
  }
}

/// Improve references to headings
///
/// Our headings are bilingual and the numbers need special formatting.
/// Therefore, we have to override the default implementation.
///
/// Also, we want labeled headings to have anchors for permalinks.
/// https://github.com/typst/typst/issues/7381
///
/// Usage: `#show: improve-heading-refs`
#let improve-heading-refs(body) = {
  show heading: it => {
    let has-label = it.at("label", default: none) != none
    let tag = "h" + str(it.level + 1)

    if it.numbering == none {
      if has-label {
        // Add id to headings in html if there exists a label
        html.elem(tag, attrs: (id: str(it.label)), it.body)
      } else {
        it
      }
    } else {
      html.elem(
        tag,
        // Add id to headings in html if there exists a label
        attrs: if has-label { (id: str(it.label)) } else { (:) },
        {
          // Wrap the numbering with a class
          html.span(counter(heading).display(it.numbering), class: "secno")
          [ ]
          it.body
        },
      )
    }
  }
  // https://github.com/Glomzzz/typsite/blob/c5f99270eff92cfdad58bbf4a78ea127d1aed310/resources/root/lib.typ#L155-L167
  show ref: it => {
    let el = it.element
    if el != none and el.func() == heading {
      // Override heading references.
      link(
        el.location(),
        // `§` is agnostic to the language.
        // There should be no space between `§` and the numbers, so we cannot set `heading.supplement`.
        numbering("§" + el.numbering, ..counter(heading).at(el.location())),
      )
    } else {
      // Other references as usual.
      it
    }
  }
  body
}

/// A collection of all fixes
#let html-fix(body) = {
  show: improve-heading-refs
  show image: external-image
  body
}
